### ISSUE TITLE
Automatic file creation for batches

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/projects.ce.pdn.ac.lk#26]
Need to update the python script to automatically create batch files under each category at the end of the repository file creation.

**Comment by NuwanJ** [comment]
It is better to use a better strategy for file creation since the current implementation is a kind of brute force approach and increasing the build time by a  significant amount 

The site generator's liquid syntax is not much intelligent, and most of the page orderings were handles by 2 nested for loops,  so it is better to filter out unnecessary batches by the python script itself.

And it is required to create the 'index.md' files under /docs/categories if not exists.

**Comment by Akilax0** [comment]
yes I understand the issue. Ill look into it

**Comment by Akilax0** [comment]
I think i made md file creation for batches more efficient now. And about index.md files when generating them what should the description be
