### ISSUE TITLE
Search bar option 

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/projects.ce.pdn.ac.lk#54]
It is possible to implement a serverless search bar using **Lunr**. Some integrations are already done and need to create the GUI part 

Useful Resources:
- https://blog.webjeda.com/instant-jekyll-search/
- https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/

**Comment by Akilax0** [comment]
ok Ill look into it
